melix/astro4j

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/align/Aligner.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/crop/Cropper.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/align/AlignerTest.groovy
There was a bug in case the tilt was too large, which caused the image to be truncated and not centered. This commit fixes the problem, as well as changing how square cropping is done in order to have consistent output sizes.
=> Fix tilt image correction

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
By performing an ellipse regression on corrected samples instead of doing edge detection and re-sampling on the corrected image.
Fixes #35
=> Rework how the virtual eclipse is produced

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/BandingReduction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/ImageUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/AnalysisUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/expr/ImageExpressionEvaluatorTest.groovy
This function can be called with `remove_bg(img;tolerance)`. It will use the ellipse mask to determine pixels which are outside of the sun disk, then compute the average of the image outside of the disk. It will then attempt to remove the background while preserving areas which are close to the limb.
=> Add a background removal function

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/ShiftCollectingImageExpressionEvaluator.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ime/ImageMathTextArea.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
After processing an image, we enable the image math editor on the right. This editor allows working with image shifts which are already computed. However, sometimes you want to try with other parameters, and it would be useful to be able to recompute with new image shifts. This is what this commit does, by automatically reprocessing the video if image shifts are missing.
=> Make it possible to re-execute scripts when image shifts are missing

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ForkJoinContext.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ForkJoinParallelExecutor.java
There was a bug in the parallel executor, which made it that the blocking call wasn't using the semaphore, resulting in too many tasks being executed concurrently. In practice, it meant we could, in batch mode, read several SER files in parallel when in practice we wanted to restrict this to a single file.
=> Fix io executor not blocking

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java
When opening process params: it was easy to forget to change it.
=> Preserve previously selected wavelength

jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/ExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/DefaultImageScriptExecutor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AbstractFunctionImpl.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/BackgroundRemoval.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/DiskFill.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/EllipseFit.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/FixBanding.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java
This makes it possible to apply some functions _after_ cropping. Previously, some functions like disk_fill or fix_banding only worked if applied before cropping. Now, there's a new function which allows performing ellipse fitting on an image, and that can be used as a parameter to these functions.
=> Add ellipse fitting to image math

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/ImageUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
JPEG doesn't support 16-bit greyscale files, so when we're saving such a mono file, we need to convert it to an RGB image.
=> Fix saving of mono JPEG files

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ScriptSupport.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
This commit adds support for computing an "average" ellipse or process parameters when using aggregate functions like avg, median, ... so that for example we can produce virtual eclipses or technical cards in a batch script.
=> Compute average params (ellipse, process params) on aggregate functions

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ScriptSupport.java
It was possible for operations, e.g img(0)+img(1) to result in images which would exceed the 0-65535 range.
=> Make sure ImageMath operators result in 16-bit values

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java
Now that we keep ellipse metadata on images, it is no longer necessary to perform a new ellipse fit on each image when performing a radius rescale. Ellipse fit is kept in case the metadata is not available (e.g when loading jpg files).
=> Use ellipse metadata for radius rescale

jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/helium-processing.math
By removing the removal of background, since it removes too much details, especially at the limb.
=> Fix helium processing script

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ContrastAdjustmentStrategy.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java
The previous implementation was truncating, but not expanding the range afterwards, which led to greyish images instead of saturated ones.
=> Fix contrast adjustment strategy

jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
One can now go on the "profile" tab of an image, which shows the wavelength intensity per pixel shift. By clicking on a node, it is possible to start a process at that pixel shift.
=> Add an option to process a pixel shift from the profile

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/stacking/StackingAndMosaicController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/JSolExInterface.java
It was possible, when using scripts, that the parent directory where to save animations didn't exist. This commit fixes this problem and also makes sure that the tabs are open when using the image math editor.
=> Fix animation sometimes not loaded

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ArcsinhStretchingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/BackgroundRemoval.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/CoronagraphTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/AnalysisUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
This image will now use background modelization to further improve constrast while not saturating pixels.
Here's a sample image with JSol'Ex 2.1.0:
The same image with JSol'Ex 2.1.1 (this commit):
And the same image processed with INTI 5.0.0 for comparison:
=> Improve virtual eclipse image

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java
If the network wasn't available for some reason, the version check could block the UI, making it unresponsive.
=> Fix version check blocking the UI

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
This commit fixes a performance issue, where the same frame was decoded multiple times in parallel. In fact, only the reconstruction should be done concurrently.
=> Fix frames being decoded multiple times

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/DynamicStretchStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
This commit improves how the protus image is blend into the main image when using the autohistogram function. This fixes an issue with solar limbs sometimes being too much lightened.
=> Improve blending of protus images in autohistogram

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectralRay.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/spectrum/SpectrumAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralRayEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java
This commit adds support for spectral lines autodetection. The algorithm will try to match the profile with a reference profile, as found in the BASS2000 database. It will also try to find the correct binning.
=> Add spectral line autodetection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/CaptureSoftwareMetadataHelper.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java
It appears that the Sharpcap format is not consistent over versions. This commit makes sure that we can parse the binning whether it consists of a single number (e.g 2) or a matrix (2x2).
In addition, we make sure that if reading of metadata fails, it doesn't block processing.
=> Fix parsing of binning

jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java
In the panels, there was a 10x factor between the real angstrom shift and the one that was displayed.
=> Fix pixel shift to Angstrom conversion in legend

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/MagnitudeBasedSunEdgeDetector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, math/src/main/java/me/champeau/a4j/math/regression/LinearRegression.java
This commit fixes the polynomial detection for some edge cases. It appears that in some videos, the first and last lines are too dark and can be confused with the actual line that we want to detect. To avoid this, we're filtering the lines so that they are not too close to the edges.
The average image computation is also modified in order to keep only the brightest frames. This is done by sampling frames in the video file in the beginning, and this is more accurate than the initial detection algorithm.
In addition this fixes a bug where the polynomial regression algorithm could return an empty array, in which case it means that detection failed.
Fixes #263
=> Fix polynomial detection

build-logic/src/main/kotlin/me.champeau.astro4j.jfxapp.gradle.kts, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FileBackedImage.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/LogbackConfigurer.java
This commit fixes a race condition which could lead to incorrectly reconstructed images. A typical symptom was that from one run to the other the image was slightly different. In some rare cases where the image was having a large tilt, this could even lead to completely broken geometry correction.
=> Fix race condition when reconstructing images

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java
This should improve reactivity, especially on slower systems. Before, all images were stretched in parallel, which could lead to a UI which would not display any image before seconds.
=> Defer stretching to when an image is selected

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/CategoryPane.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties
By default, panels are generated with "half" of the range of pixel shifts, in order to reduce their size. This commit introduces a new checkbox for people who want to see the full range.
Fixes #273
=> Add ability to generate full range panels

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/Corrector.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java
When an image is autocropped, it is not necessary to resize the image so that the solar disk is not truncated, because we know that it is already centered.
=> Fix rotation with P angle changing the cropped image dimensions

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Rotate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/spectrum/SpectrumAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ContrastAdjustmentStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/MagnitudeBasedSunEdgeDetector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/Redshift.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/RedshiftArea.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DefaultImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DiscardNonRequiredImages.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/NamingStrategyAwareImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/NoOpImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/RenamingImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FitsUtils.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger.fxml
This commit reworks speed detection to be more accurate. It should result in less false positives, while more accurately representing the areas where speeds are detected.
The speed images are assigned a unique id, so that it is easier to locate them and match images together.
In addition, the spectrum debugger will now show detected shifts, and the generated debug images will tell where shifts are detected.
=> Improve speed detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchProcessingContext.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Under Windows 11, the text may not appear correctly so it's important that the alerts are resizable Fix memory consumption issue when reconstructing images.
=> Use an AlertFactory so that we have all alerts configured the same

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/ImageAnalysis.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This will improve processing of dark images, in particular calcium lines.
=> Ignore gamma correction if original image is too dark

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DisplayCategory.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/GeneratedImageKind.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
As they are fairly useful, the debug images are now promoted to normal images. In order to better classify images a new "redshift" category was added.
=> Promote redshift debug images to dedicated category

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/ImageAnalysis.java
Counting the number of distinct pixel values is too expensive and wasn't used in any case.
=> Fix excessive memory consumption of image analysis

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
In some expressions like `find_shift(...)+1`, we can't precompute the pixel shift value. In this case, we introduce a fallback which will reconstruct the image on demand.
=> Fix missing images when a shift is dynamic

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java
This commit fixes a serious computation error of positions of redshifts when the geometry correction was important (e.g oval disks or high tilt) or flipped.
This caused the redshift images/panels/animations to be misplaced.
=> Fix redshift position when image is flipped or geometry corrected

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/ImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectrumParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/LinearStrechingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/PixelShiftRange.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SpectralLineFrameImageCreator.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
In some cases, it's possible for the user to directly or indirectly request an image at some pixel shift which would go beyond the cropping window.
If that happens, the software will now warn the user and pick the closest available pixel shift.
Fixes #334
=> Make sure that requested pixel shifts are available

jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Images which are composites (e.g a stack from multiple images) don't have the required reference information for logging the position in the source image. This caused the crop action to do nothing on images from batch mode, for example. This commit fixes the problem.
=> Fix dynamic cropping of composite images

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
When an image was eagerly loaded and that alignment was deferred, the scroll pane position was set too early.
=> Fix alignment button behavior

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ArcsinhStretchingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/DynamicStretchStrategy.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This commit improves the autostretch algorithm to avoid saturation which often happens with calcium images.
=> Improve autostretch

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/StretchingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/AdvancedParamsController.java
The autostretch strategy in particular is very inefficient in case of "empty" images.
=> Fix performance issue when collecting shifts

build-logic/src/main/kotlin/me.champeau.astro4j.jfxapp.gradle.kts, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AbstractFunctionImpl.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Animate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/FfmegEncoder.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This commit reduces the amount of memory used when creating large animation or panels. Panels are now limited to a maximum size of 7680 pixels.
=> Fix panel/animation creation with large files

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java
Linear reconstruction can cause artifacts in narrow lines. This commit introduces averaging with +=0.5 pixels in order to reduce these artifacts.
=> Improve reconstruction to mitigate artifacts

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Animate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/FfmegEncoder.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FileBackedImage.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/TemporaryFolder.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/VersionUtil.java, jsolex-server/src/main/java/me/champeau/a4j/jsolex/server/ImagesStore.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/CustomAnimationCreator.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralRayEditor.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This commit reworks the temporary folder handling, so that we delete files from old sessions. We do this by restructuring the folder, so that it's named against the current PID. If a process is still alive, then we won't delete it.
Fixes #500
=> Rework temporary folder cleanup

jserfile/src/main/java/me/champeau/a4j/ser/SerFileReader.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Before this change, we were looking for the maximum pixel depth only around the middle of the SER file. While this worked for most cases, it didn't when, for example, the SER file consisted of a long black range of frames, then the sun only in the end (or the other way around). Now sampling is regular around the whole SER file, we take a look at 10% of the frames.
Fixes a bug discovered while processing a file from @splanquart
=> Make SER pixel depth recognition more robust

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This can be useful when using scripts and that you need to see the result of an image _without_ any post-processing.
=> Make stretching configurable in image view

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This algorithm improves prominence stretching, now that we use background modeling, we can more reliably use arcsin stretching for the prominences, then blend the result.
=> Improve prominence stretching

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
The polynomial was recomputed for each line, but we didn't need to do this.
=> Fix performance issue with redshift detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/ImageBandingCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This commit fixes the position of active regions when a rotation is applied. To fix this, the rotations are now applied before the process is started, which required some adjustment in processing and displaying images:
- rotations are applied to the reconstructed image
- the only rotations applied in the image view are these that the user applied manually _after_ processing
- the `img(xxx)` image will now have the rotations applied
- the initial banding correction needs to account for the rotations which have been applied
=> Fix orientation of active regions

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SetupsIO.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
For some reason it seems that the alt-az mode is causing more troubles than it fixes with sunscan: the parallactic angle correction is not required!
=> Fix sunscan images wrongly oriented

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
When auto constrast is applied on a binary image (e.g a masked image) then the pedestral could be negative.
Fixes #612
=> Fix array index out of bounds

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This is a small breaking change but this is the right thing to do.
Fixes #660
=> No longer stretch image math images by default
