melix/astro4j

README.md, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml
This will allow the user to enter whatever value they need.
Fixes #30
=> Replace pixel shift slider with text field

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
=> Display all selected files on separate lines

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ForkJoinContext.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ForkJoinParallelExecutor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/LogbackConfigurer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java
=> Use a separate log file for each processed file

.gitignore, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/CutoffStretchingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/WorkflowState.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/align/Aligner.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/align/AlignerTest.groovy
This fixes edge detection by using a dynamic sensitivity algorithm instead of using a fixed constant. This makes the algorithm more flexible, at the cost of having ot perform more searches of samples.
In addition, outlier detection algorithm has been improved, by filtering pixels which are too far from the average distance of 2 samples.
Fixes #37
=> Rework edge detection

jsolex-cli/src/main/java/me/champeau/a4j/jsolex/cli/Main.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectralRay.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectralRaySerializer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectrumParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SpectralLineFrameImageCreator.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzerTest.groovy, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralRayEditor.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml
We're now simply using the darkest pixel of the line to create samples.
=> Simplify spectral line detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java
=> Add bilinear interpolation during shear transform

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger.fxml
=> Add fine tuning controls to spectrum debugger

jsolex-cli/src/main/java/me/champeau/a4j/jsolex/cli/Main.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/file/FileNamingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ExtraParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/FileNamingPatternsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/NamedPattern.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/NamingPatternEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralRayEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/naming-patterns.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/naming-patterns.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/naming-patterns_fr_FR.properties
=> Add date(time) patterns

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/DefaultImageScriptExecutor.java
=> Fix labels using reserved keywords

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/GeometryParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/GeometryParamsSerializer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/AbstractTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/CoronagraphTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/ImageBandingCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ColorizedImageWrapper.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ImageWrapper.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ImageWrapper32.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/RGBImage.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr_FR.properties
There is now a configurable flag if this is really what the user wants.
Fixes #63
=> Reduce memory pressure by reducing not rescaling to full resolution

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/file/FileNamingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/FileNamingPatternsIO.java
=> Fix incorrect character under Windows

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/MagnitudeBasedSunEdgeDetector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java
=> Fix memory leak when reading SER files

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/frame-debugger_fr_FR.properties
=> Add a progress bar to the debugger window

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java
=> Fix incorrect channel assignment

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/imageview.fxml
Make the zoom more accessible and display coordinates of cursor. There's a zoom slider which allows zooming and the following actions are possible:
- CTLR+mouse wheel : zoom in/out
- double click : reset zoom
=> Improve image view

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageMathEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ime/ImageMathTextArea.java
The message to warn about loosing unsaved changes could be displayed multiple times.
=> Fix image saving logic

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java
=> Add zoom to debugger

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Loader.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/align/Aligner.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/crop/Cropper.java
This new function can be used to load another image from disk, for example an image from a different session. This can be useful when for example you need to perform operations like substration on images with different exposures.
=> Add a `load` function to load an existing image from disk

build-logic/src/main/kotlin/me.champeau.astro4j.base.gradle.kts, docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/DiskFill.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageMathEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ime/ImageMathTextArea.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/imagemath-editor.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/imagemath-editor.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/imagemath-editor_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/continuum-animation.math, jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/doppler.math, jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/helium-processing.math, jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/virtual-eclipse.math
These scripts demonstrate what can be done with ImageMath. They still have to be saved on disk for the user to apply them.
=> Add sample scripts

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/UpdateChecker.java, jsolex/src/main/java/module-info.java
In some cases, edge detection failed because the image wasn't contrasted enough.
=> Fix edge detection

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/EllipseFit.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/align/AlignerTest.groovy, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, math/src/main/java/me/champeau/a4j/math/image/BlurKernel.java, math/src/main/java/me/champeau/a4j/math/image/Kernel33.java
This method adds support for rescaling a set of images so that they all have the same disk radius (in pixels).
=> Add radius_rescale method

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ForkJoinParallelExecutor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/LoggingSupport.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageSelector.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
This new mode allows watching a directory for changes. If a new SER file is added, process will be automatically started.
=> Introduce directory watcher

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
By right clicking on an image, it is possible to open it in a new window. By combining with the watch mode, the image can automatically be updated on every new file being processed.
Closes #98
=> Add the ability to open a file in a new window

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java
So that we can make sure that a file was processed. It also adds a counter, so that we know how many images were processed.
=> Add file name in popup window viewer

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
Instead of relying on focus, we'll read the file size of new files. If the size hasn't changed after 2.5 seconds, then we consider that write is complete and start processing.
=> Automatically start processing in watch mode after x seconds without file change

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/RotationCorrector.java, math/src/main/java/me/champeau/a4j/math/image/ImageMath.java
In particular, for the negative image. We're now computing the average of mixing pixels and using it to fill.
=> Improve filling when rotating for P angle

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Rotate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java, math/src/main/java/me/champeau/a4j/math/regression/Ellipse.java
This commit fixes the fact that the detected ellipses were not corrected after a rotation or rescale.
=> Fix rotation/rescale not changing the detected ellipse

jsolex-cli/src/main/java/me/champeau/a4j/jsolex/cli/LoggingListener.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ClaheStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/DebugImageHelper.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java
For improved image quality by default.
=> Tweak default CLAHE parameters

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AdjustContrast.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ClaheStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/ContrastAdjustmentStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/StretchingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DopplerSupport.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/Histogram.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/JSolExInterface.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
This commit adds an image histogram graph, which is available via a tab on the right of the application.
=> Add histogram tab

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SolarParameters.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SolarParametersUtils.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java
If the file extension is .SER (not .ser), then the file chooser wasn't showing the file. Very unfortunate.
=> Fix SER files not being found when extension is uppercase

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Animate.java
Previously, it was only possible using mono images or colorized images.
=> Add support for animations using RGB images

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/DistortionCorrection.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SpectralLineFrameImageCreator.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzerTest.groovy, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, math/src/main/java/me/champeau/a4j/math/regression/LinearRegression.java, math/src/main/java/me/champeau/a4j/math/tuples/DoublePair.java, math/src/main/java/me/champeau/a4j/math/tuples/DoubleQuadruplet.java, math/src/main/java/me/champeau/a4j/math/tuples/DoubleTriplet.java, math/src/test/groovy/me/champeau/a4j/math/LinearRegressionTest.groovy
This provides higher accuracy when reconstructing the image.
=> Use 3rd order polynomial for distortion correction

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java
The raw image should be unprocessed (except for geometric correction) but it was the CLAHE image which was saved as raw.
=> Fix CLAHE image replacing raw image

math/src/main/java/me/champeau/a4j/math/image/Deconvolution.java
Fixes the exception:
```
Java runtime version 21.0.1
Vector API support is available and enabled (disable by setting VECTOR_API environment variable to false)
Fichiers sélectionnés D:\FireCapture_v2.7\captures\Sun\220723\2023-07-22-1539_5-U-RGB-Sun.ser
No config file found at C:\Users\jfd38\.jsolex\filename-patterns.json. Using default patterns
Error while processing
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown …
```
=> Fix number format error when starting process

jsolex/src/main/java/me/champeau/a4j/jsolex/app/Configuration.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageMathEditor.java
Last directory was currently only saved for SER files.
=> Remember last used directory for scripts

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/LogbackConfigurer.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/syntax.css
Errors will now be showed in red in the console.
=> Use a colored log output

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/MosaicComposition.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/BackgroundRemoval.java, math/src/main/java/me/champeau/a4j/math/regression/LinearRegression.java
This improves the mosaicing process by avoiding zero pixels.
=> Normalize background before mosaicing

jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java
Before this commit, the images were added to tabs and automatically selected as they were generated. User feedback showed that it would be better to have a particular image always displayed by default, so the tab will only be selected if that is that particular image.
=> Display a particular image by default

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/MosaicComposition.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Stacking.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/AnalysisUtils.java
- fix histogram normalization
- use automatic tile sizes for mosaicing
=> Mosaic generation fixes

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/ImageUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ImageSaver.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java
In some cases, the temporary file which was used to display an image was deleted before the image could be displayed.
=> Fix images not appearing in interface

build-logic/src/main/kotlin/me.champeau.astro4j.jfxapp.gradle.kts, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AbstractFunctionImpl.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AdjustContrast.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Animate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/BackgroundRemoval.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Clahe.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Colorize.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Convolution.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/DiskFill.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/EllipseFit.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/FixBanding.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/GeometryCorrection.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Inverse.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Loader.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/MosaicComposition.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Rotate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Saturation.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/SimpleFunctionCall.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Stacking.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Stretching.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/StackingWorkflow.java
Scripts will now send more messages to the status bar, making them less likely to feel stuck.
=> Improve status bar when executing scripts

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java
In some cases the edge detection threshold was too low, leading to incorrect polynoms.
=> Fix sun edge detection

README.md, build-logic/build.gradle.kts, build-logic/src/main/java/me/champeau/astro4j/SpectrumFileConverter.java, gradle.properties, jsolex-core/build.gradle.kts, jsolex-core/src/bass2000/README.md, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/spectrum/ReferenceIntensities.java, jsolex-core/src/main/java/module-info.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties, licenses/spectrum/LICENSE
This profile lets you compare the profile of your acquisition with a reference profile from the BASS2000 database.
=> Add reference profile to the profile tab

gradle.properties, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/MosaicComposition.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Stacking.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/StackingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/BackgroundOperations.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ImageWrapper.java
There was an error silently thrown when building mosaics or stacking images.
=> Fix stacking and mosaic composition

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/CategoryPane.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java
- Move close button to the right
- Add new fitting buttons for image zoom
=> UI improvements

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This improves edge detection in particular for calcium images.
=> Refine edge detection

jserfile/src/main/java/me/champeau/a4j/ser/SerFileReader.java, jserfile/src/main/java/me/champeau/a4j/ser/bayer/RGBImageConverter.java
It turns out that the image depth found in SER file metadata cannot be trusted. Sometimes it says 16 bit when in practice it's 12 bits.
This commit fixes the reader by sampling frames and deducing the max pixel depth from this sample.
=> Fix conversion of frames

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/GeneratedImageKind.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/Corrector.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java
This makes it easier to proceed with the correct rotations/flips without having to restart a whole process.
Fixes #266
=> Add rotation/flip buttons

jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java
This is easier than rotating twice then performing vertical flip
=> Add horizontal mirror

jsolex/src/main/java/me/champeau/a4j/jsolex/app/AlertFactory.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageMathEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SetupEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectroHeliographEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/stacking/PanelCard.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchProcessingContext.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Under Windows 11, the text may not appear correctly so it's important that the alerts are resizable
=> Use an AlertFactory so that we have all alerts configured the same

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java
This commit reworks (once again) edge detection to make it more reliable. This will result in better eclipse images, as well as better detection of difficult lines like calcium.
=> More reliable edge detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java
This commit introduces background normalization during ellipse fitting. This turns out to greatly help with difficult edge detection, in particular near UV (calcium).
=> Use background normalization in ellipse fitting

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/HeliumLineProcessor.java
=> Fix Helium mono image being overwritten

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ExposureCalculator.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/exposure-calculator.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/exposure-calculator.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/exposure-calculator_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Since the FPS is often the limit.
=> Show FPS in optimal exposure calculator

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/LinearStrechingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/StretchingChain.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/ColorizedImageWrapper.java
This makes sure that in the case of a stretching chain, the proper stretching is applied to colorized/RGB images.
=> Fix stretching of colorized images

jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
By avoiding to recompute autostretched images for each animation.
=> Improve performance of redshift animations/panels creation

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Ability to use polynomial from a happy frame

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Let the user specify which redshift images to generate

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/AverageImageCreator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/DistortionCorrection.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/FlatCorrection.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzer.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SpectralLineFrameImageCreator.java, jsolex-core/src/test/groovy/me/champeau/a4j/jsolex/processing/sun/SpectrumFrameAnalyzerTest.groovy, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This is especially visible in calcium images.
=> Improve spectral line detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/FlatCorrection.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Fix excessive flat correction

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/EnhancementParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
It's not robust enough yet.
Fixes #364
=> Make artificial flat correction optional

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Fix contrast slider behavior

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectrumBrowser.java
=> Fix behavior of the pixel size box

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AbstractFunctionImpl.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FilesUtils.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/CustomAnimationCreator.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Fix redshift animation creation

jsolex/src/main/java/me/champeau/a4j/jsolex/app/Configuration.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/AdvancedParamsController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageMathEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/script/JSolExScriptExecutor.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/advanced-params.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/advanced-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/advanced-params_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
The wait time is configurable via the "advanced parameters" in the main menu.
Fixes #378
=> Make the wait time in watch mode configurable

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/ImageMathScriptExecutor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/file/FileNamingStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DefaultImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DiscardNonRequiredImages.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/DopplerSupport.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/HeliumLineProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/NamingStrategyAwareImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/NoOpImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/RenamingImageEmitter.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/StackingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/DebugImageHelper.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/NamingPatternEditor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/RedshiftImagesProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
In addition to the extracted version.
Fixes #380
=> Produce "direct" helium line image

jsolex-core/src/main/java/module-info.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/Configuration.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectrumBrowser.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
- use a cropped window for polynomial detection
- fix dispersion correction causing misalignment after detection
- remember the last directory used
=> Improve line identification

README.md, gradle.properties, jserfile/src/main/java/me/champeau/a4j/ser/SerFileReader.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/event/ProcessingEventListener.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/event/ReconstructionDoneEvent.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ReconstructionView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/WithRootNode.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This new view allows clicking a pixel in the reconstruction view. When doing so, the frame corresponding to this pixel will be displayed, as well as a red cross showing the particular pixel in the frame which was used to construct the image.
Fixes #386
=> Enhanced reconstruction view

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Filtering.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/SourceInfo.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FitsUtils.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/MetadataSupport.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This function allows filtering a list of images based on a particular criteria.
=> Introduce `filter` function

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/SpectralLineFrameImageCreator.java
This can happen because of rounding errors and custom polynomials.
Fixes #399
=> Fix potential array index out of bounds error

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ReconstructionView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This makes the "click to frame" feature more useful, when captures are using low gain.
=> Perform stretching of recon view

jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/LogbackConfigurer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/BatchOperations.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/CategoryPane.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/MultipleImagesViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectralLineDebugger.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectrumBrowser.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ZoomableImageView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ime/ImageMathTextArea.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/app_fr_FR.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/fast-mode-open.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/fast-mode-open.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/fast-mode-open_fr_FR.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Using the "select and process" button, the file will be processed with the last used parameters.
=> Add a fast processing mode

jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/SpectrumBrowser.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/spectrum-browser.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/spectrum-browser_fr_FR.properties
This is useful for Sunscan, where the spectrum has red on top and blue at the bottom.
=> Add button to flip spectrum in browser

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/event/ProcessingDoneEvent.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/JSolEx.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/BatchItem.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/BatchModeEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr_FR.properties
to summarize the number of detected active regions and the maximal redshift.
=> Add columns to the batch view

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java
=> Use more samples when ellipse fit cannot be performed

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectroHeliograph.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectroHeliographsIO.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This fixes Helium line extraction and measured speeds.
/cc @minhlead
=> Adjust FL of SHG700

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/ser-trimmer.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/ser-trimmer_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This function returns the computed wavelength for a particular pixel shift.
=> Add `wavelen` function

docs/src/docs/asciidoc/en/jsolex.adoc, docs/src/docs/asciidoc/fr/jsolex.adoc, jsolex-core/src/main/congocc/ImageMath.ccc, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/BuiltinFunction.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/expr/ExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/DefaultImageScriptExecutor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/ImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/ShiftCollectingImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/RemoteScriptGen.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/BackgroundOperations.java, jsolex-core/src/main/java/module-info.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ime/ImageMathTextArea.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This function is an advanced function which can help with generating more images programmatically. See docs for details.
@vnp85 this is what we discussed earlier.
=> Add remote_scriptgen function

jsolex-core/src/main/functions/auto_contrast.yml, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/AdjustContrast.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/AutoStretchParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/stretching/AutohistogramStrategy.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/HeliumLineProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This fixes an issue reported by multiple users, where a thin dark line is visible:
=> Introduce parameter for autostretch proms

jsolex-core/src/main/functions/draw_globe.yml, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ExtraParams.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/GlobeStyle.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageViewer.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ProcessParamsController.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/process-params_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This new style draws the N label on the celestial north, and draws the P label on the solar north, which is a common convention in scientific images.
Fixes #579
=> Added new globe style

jsolex-core/src/main/functions/draw_text.yml, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/AbstractImageExpressionEvaluator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/ImageDraw.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
This allows using some variable tokens in text, for example to print the pixel shift.
=> Improve capabilities of DRAW_TEXT

README.md, gradle.properties, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Crop.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Rotate.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/expr/impl/Scaling.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/RequestedImages.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/EllermanBomb.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/EllermanBombs.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/GeometryCorrector.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/GeneratedImageKind.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ProcessingWorkflow.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/util/FitsUtils.java, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages.properties, jsolex-core/src/main/resources/me/champeau/a4j/jsolex/processing/util/messages_fr.properties, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ImageSelector.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/ReconstructionView.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/listeners/SingleModeProcessingEventListener.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection.fxml, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/image-selection_fr.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages.properties, jsolex/src/main/resources/me/champeau/a4j/jsolex/app/messages_fr.properties, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
=> Implement Ellerman Bomb detection

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/AverageImageCreator.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/detection/PhenomenaDetector.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md, math/src/main/java/me/champeau/a4j/math/image/ImageMath.java
Avoid overuse of parallel of parallel, which was accidental.
=> Optimize performance in full processing mode

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/ProcessParamsIO.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Not sure in which situation this could happen, but it did!
Fixes #615
=> Protect against potential NPE

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/workflow/ReferenceCoords.java, jsolex/src/main/java/me/champeau/a4j/jsolex/app/jfx/Corrector.java
This caused cropping and SER extraction to be wrong.
=> Fix incorrectly stored rotation

jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/SolexVideoProcessor.java, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/tasks/EllipseFittingTask.java, jsolex/src/main/resources/me/champeau/a4j/jsolex/templates/corona.math, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md
Detailed analysis: http://www.astrosurf.com/topic/177392-couronne-solaire-e-9-juillet-2025/?tab=comments#comment-2533766
=> Improve corona extraction script

jsolex/src/main/resources/me/champeau/a4j/jsolex/app/assisted-ellipse-fitting.fxml
=> Fix button bar disappearing if window is too small

.github/workflows/distributions.yml, jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/sun/BandingReduction.java, jsolex/src/main/resources/whats-new.md, jsolex/src/main/resources/whats-new_FR.md, math/src/main/java/me/champeau/a4j/math/MathUtils.java, math/src/test/groovy/me/champeau/a4j/math/MathUtilsTest.groovy
This commit improves the correction, especially polar caps, and reduces the risks of over-correcting filaments.
=> Improve banding correction
